apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: the-task
spec:
  inputs:
    params:
      - name: task-pvc
      - name: aDefaultEmptyValue
      - name: anEmptyValueFromBinding
      - name: anEmptyValueFromEnvProperty
  steps:
    - name: fetch-git-token
      image: ibmcom/pipeline-base-image
      env:
        - name: HOME
          value: "/root"
        - name: A_DEFAULT_EMPTY_VALUE
          value: $(inputs.params.aDefaultEmptyValue)
        - name: AN_EMPTY_VALUE_FROM_BINDING
          value: $(inputs.params.anEmptyValueFromBinding)
        - name: AN_EMPTY_VALUE_FROM_ENV_PROPERTY
          value: $(inputs.params.anEmptyValueFromEnvProperty)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          env | sort
          ibmcloud doi
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /steps
          name: steps-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
